'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');
const {Broker}=require('../desktop/broker.cjs');const {Store,Vault}=require('../desktop/store.cjs');const {temp,secure}=require('./helpers.cjs');
async function fixture(t){const root=await temp(t),runs=[],adapters=[];const factory=options=>{const a={options,closed:false,connect:async()=>({description:'Fixture connected'}),close:()=>{a.closed=true;},run:ctx=>new Promise((resolve,reject)=>{runs.push({ctx,resolve,reject,agent:options.agent});ctx.signal.addEventListener('abort',()=>reject(new Error('Cancelled')),{once:true});})};adapters.push(a);return a;};const b=new Broker({store:new Store(root),vault:new Vault(root,secure()),emit:()=>{},approve:async()=>true,adapterFactory:factory});await b.init();t.after(()=>b.close());return {b,root,runs,adapters};}
const apiAgent=(name,port)=>({name,provider:'hermes',protocol:'openai',transport:'http',endpoint:`http://127.0.0.1:${port}/v1`,model:'hermes-agent'});
const tick=()=>new Promise(r=>setImmediate(r));
test('broker persists separate agents and never sends tokens to the renderer',async t=>{const {b,root}=await fixture(t);const a=await b.saveAgent({agent:apiAgent('Research',8642),token:'gateway-supersecret'});assert.equal(b.snapshot().agents[0].hasToken,true);assert(!JSON.stringify(b.snapshot()).includes('gateway-supersecret'));assert(!String(await fs.readFile(path.join(root,'workspace.json'))).includes('gateway-supersecret'));await b.connect(a.id);assert.equal(b.snapshot().agents[0].status,'connected');});
test('broker rejects duplicate connections but accepts distinct Hermes instances',async t=>{const {b}=await fixture(t);await b.saveAgent({agent:apiAgent('one',8642)});await assert.rejects(()=>b.saveAgent({agent:apiAgent('renamed same endpoint',8642)}),/already exists/);await b.saveAgent({agent:apiAgent('two',8643)});assert.equal(b.data.agents.length,2);});
test('same-agent concurrent sends are rejected before asynchronous storage',async t=>{const {b,runs}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)});await b.connect(a.id);const first=b.send({agentId:a.id,text:'hello'});await assert.rejects(()=>b.send({agentId:a.id,text:'duplicate'}),/already working/);await first;assert.equal(runs.length,1);const done=b.turns.get(a.id).done;runs[0].resolve({});await done;assert.equal(b.data.conversations.length,1);});
test('switching agents while both stream preserves transcript and session isolation',async t=>{const {b,runs}=await fixture(t),a=await b.saveAgent({agent:apiAgent('research',8642)}),d=await b.saveAgent({agent:apiAgent('ops',8643)});await b.connect(a.id);await b.connect(d.id);const ca=await b.send({agentId:a.id,text:'research only'});const cd=await b.send({agentId:d.id,text:'ops only'});await b.select(a.id);const done=[b.turns.get(a.id).done,b.turns.get(d.id).done];for(const run of runs){run.ctx.onEvent({type:'text',text:run.agent.name});run.resolve({externalSessionId:run.agent.id});}await Promise.all(done);assert.equal(b.histories.get(ca.conversationId)[1].content,'research');assert.equal(b.histories.get(cd.conversationId)[1].content,'ops');assert.equal(b.data.conversations.find(c=>c.id===ca.conversationId).externalSessionId,a.id);});
test('foreign-agent conversation IDs cannot be sent',async t=>{const {b}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)}),d=await b.saveAgent({agent:apiAgent('two',8643)});const c=await b.newConversation(a.id);await b.connect(d.id);await assert.rejects(()=>b.send({agentId:d.id,conversationId:c.id,text:'no'}),/does not belong/);assert.equal(b.turns.size,0);});
test('stopping keeps partial output and marks the connection disconnected',async t=>{const {b,runs}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)});await b.connect(a.id);const c=await b.send({agentId:a.id,text:'start'});const done=b.turns.get(a.id).done;runs[0].ctx.onEvent({type:'text',text:'partial'});b.stop(a.id);await done;assert.equal(b.histories.get(c.conversationId)[1].status,'cancelled');assert.equal(b.histories.get(c.conversationId)[1].content,'partial');assert.equal(b.runtimeFor(a.id).status,'disconnected');});
test('removing an active connection does not recreate deleted transcripts',async t=>{const {b,root}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)});await b.connect(a.id);const c=await b.send({agentId:a.id,text:'start'});await b.removeAgent(a.id);await assert.rejects(()=>fs.stat(path.join(root,'conversations',c.conversationId+'.json')),e=>e.code==='ENOENT');assert.equal(b.data.agents.length,0);assert.equal(b.data.conversations.length,0);});
test('stopping during a pending disk write does not launch the agent turn',async t=>{const {b,runs}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)});await b.connect(a.id);const p=b.send({agentId:a.id,text:'never sent'});b.stop(a.id);await assert.rejects(()=>p,/cancelled/);assert.equal(runs.length,0);assert.equal(b.turns.size,0);});
test('host removal is blocked while saved agent connections reference it',async t=>{const {b}=await fixture(t),h=await b.saveHost({alias:'my-vps'});await b.saveAgent({agent:{...apiAgent('remote',8642),transport:'ssh',hostId:h.id}});await assert.rejects(()=>b.removeHost(h.id),/Remove or reassign/);});
test('workspace state and completed transcripts survive a fresh broker instance',async t=>{const {b,runs,root}=await fixture(t),a=await b.saveAgent({agent:apiAgent('one',8642)});await b.connect(a.id);const c=await b.send({agentId:a.id,text:'remember'});const done=b.turns.get(a.id).done;runs[0].ctx.onEvent({type:'text',text:'saved'});runs[0].resolve({externalSessionId:'native-session'});await done;await b.close();const next=new Broker({store:new Store(root),vault:new Vault(root,secure()),emit:()=>{},approve:async()=>false});await next.init();assert.equal(next.histories.get(c.conversationId)[1].content,'saved');assert.equal(next.data.conversations[0].externalSessionId,'native-session');assert.equal(next.snapshot().agents[0].status,'disconnected');await next.close();});
