'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const http=require('node:http');
const {HttpAdapter,SSE}=require('../desktop/adapters/http.cjs');const {context}=require('./helpers.cjs');
async function server(t,handler){const s=http.createServer(handler);await new Promise(r=>s.listen(0,'127.0.0.1',r));t.after(()=>new Promise(r=>{s.closeAllConnections();s.close(r);}));return `http://127.0.0.1:${s.address().port}/v1`;}
function sse(res,text,done=true){res.writeHead(200,{'content-type':'text/event-stream'});res.write('data: '+JSON.stringify({choices:[{delta:{content:text}}]})+'\n\n');res.end(done?'data: [DONE]\n\n':'');}
test('SSE parser handles fragmented CRLF, multiline data and completion',()=>{const events=[],p=new SSE((event,data)=>events.push({event,data}));p.feed('event: status\r');p.feed('\ndata: line1\r\ndata: line2\r\n\r');p.feed('\ndata: [DONE]\n\n');assert.deepEqual(events,[{event:'status',data:'line1\nline2'},{event:'message',data:'[DONE]'}]);});
test('SSE parser rejects oversized protocol events',()=>assert.throws(()=>new SSE(()=>{}).feed('a'.repeat(1024*1024+1)),/limit/));
test('real loopback HTTP integration authenticates models, streams text and preserves full stateless history',async t=>{const bodies=[];const endpoint=await server(t,async(req,res)=>{assert.equal(req.headers.authorization,'Bearer test-key');if(req.url==='/v1/models'){res.setHeader('content-type','application/json');res.end(JSON.stringify({data:[{id:'hermes-agent'}]}));return;}let raw='';for await(const c of req)raw+=c;bodies.push(JSON.parse(raw));sse(res,'Hello from fixture');});const a=new HttpAdapter({agent:{provider:'hermes',transport:'http',endpoint,model:'hermes-agent'},token:'test-key'});assert.deepEqual((await a.connect()).models,['hermes-agent']);const out=[];await a.run(context({messages:[{role:'user',content:'first',status:'done'},{role:'assistant',content:'reply',status:'done'},{role:'user',content:'next',status:'done'}],onEvent:e=>out.push(e)}));assert.equal(out[0].text,'Hello from fixture');assert.equal(bodies[0].messages.length,3);assert.equal(bodies[0].stream,true);});
test('OpenClaw uses one stable conversation key and sends only the newest message',async t=>{let body;const endpoint=await server(t,async(req,res)=>{let raw='';for await(const c of req)raw+=c;body=JSON.parse(raw);sse(res,'ok');});const a=new HttpAdapter({agent:{provider:'openclaw',transport:'http',endpoint,model:'openclaw/research'}});await a.run(context({text:'new message',messages:[{role:'user',content:'old',status:'done'}]}));assert.equal(body.user,'agenthub:conversation-one');assert.deepEqual(body.messages,[{role:'user',content:'new message'}]);});
test('failed earlier turns are not replayed into stateless history',async t=>{let body;const endpoint=await server(t,async(req,res)=>{let raw='';for await(const c of req)raw+=c;body=JSON.parse(raw);sse(res,'ok');});const a=new HttpAdapter({agent:{provider:'hermes',endpoint,model:'hermes-agent'}});await a.run(context({messages:[{role:'user',content:'cancelled task',status:'done'},{role:'assistant',content:'partial',status:'cancelled'},{role:'user',content:'new task',status:'done'}]}));assert.deepEqual(body.messages,[{role:'user',content:'new task'}]);});
test('dropped streams preserve partial text and reject false success',async t=>{const endpoint=await server(t,(req,res)=>sse(res,'partial',false));const out=[];await assert.rejects(()=>new HttpAdapter({agent:{endpoint,model:'m'}}).run(context({onEvent:e=>out.push(e)})),/completion marker/);assert.equal(out[0].text,'partial');});
test('authentication errors do not include returned server secrets',async t=>{const endpoint=await server(t,(req,res)=>{res.writeHead(401);res.end('DO_NOT_SHOW');});await assert.rejects(()=>new HttpAdapter({agent:{endpoint}}).connect(),e=>/authentication/.test(e.message)&&!e.message.includes('DO_NOT_SHOW'));});
test('redirects are not followed with gateway bearer credentials',async t=>{let hits=0;const endpoint=await server(t,(req,res)=>{hits++;res.writeHead(302,{Location:'/stolen'});res.end();});await assert.rejects(()=>new HttpAdapter({agent:{endpoint},token:'secret'}).connect());assert.equal(hits,1);});
test('client-side tool requests are refused rather than faked as executed',async t=>{const endpoint=await server(t,(req,res)=>{res.setHeader('content-type','application/json');res.end(JSON.stringify({choices:[{message:{content:'working',tool_calls:[{id:'t'}]}}]}));});await assert.rejects(()=>new HttpAdapter({agent:{endpoint,model:'m'}}).run(context()),/client-side tools/);});
test('HTTP streaming cancellation aborts the local request',async t=>{const endpoint=await server(t,(req,res)=>{res.writeHead(200,{'content-type':'text/event-stream'});res.write('data: {"choices":[{"delta":{"content":"started"}}]}\n\n');});const abort=new AbortController();const a=new HttpAdapter({agent:{endpoint,model:'m'}});const pending=a.run(context({signal:abort.signal,onEvent:()=>abort.abort()}));await assert.rejects(()=>pending);});
test('Hermes progress events surface tool status without treating it as assistant prose',async t=>{const endpoint=await server(t,(req,res)=>{res.writeHead(200,{'content-type':'text/event-stream'});res.end('event: hermes.tool.progress\ndata: {"tool_name":"search"}\n\ndata: [DONE]\n\n');});const out=[];await new HttpAdapter({agent:{endpoint,model:'m'}}).run(context({onEvent:e=>out.push(e)}));assert.equal(out[0].type,'activity');assert.match(out[0].text,/search/);});
test('streams that finish with finish_reason but no [DONE] marker are complete answers',async t=>{const endpoint=await server(t,(req,res)=>{res.writeHead(200,{'content-type':'text/event-stream'});res.end('data: {"choices":[{"delta":{"reasoning_content":"hmm"}}]}\n\ndata: {"choices":[{"delta":{"content":[{"type":"text","text":"Hel"}]}}]}\n\ndata: {"choices":[{"delta":{"content":"lo"},"finish_reason":"stop"}]}\n\n');});const out=[];await new HttpAdapter({agent:{endpoint,model:'m',provider:'hermes'}}).run(context({onEvent:e=>out.push(e)}));assert.deepEqual(out.map(e=>e.type),['activity','text','text']);assert.equal(out[0].text,'Thinking');assert.equal(out.filter(e=>e.type==='text').map(e=>e.text).join(''),'Hello');});
test('gateway errors keep the gateway message and long chat requests disable fetch body timeouts',async t=>{const endpoint=await server(t,(req,res)=>{res.writeHead(502,{'content-type':'application/json'});res.end(JSON.stringify({error:{message:'upstream model overloaded'}}));});await assert.rejects(()=>new HttpAdapter({agent:{endpoint,model:'m',provider:'hermes'}}).run(context()),/Hermes gateway failed.*upstream model overloaded/);
  let init;const a=new HttpAdapter({agent:{endpoint:'http://127.0.0.1:1/v1',model:'m',provider:'hermes'},fetchImpl:async(_u,i)=>{init=i;return new Response('data: [DONE]\n\n',{headers:{'content-type':'text/event-stream'}});}});await fetch('http://127.0.0.1:9/').catch(()=>{});await a.run(context());assert.ok(init.dispatcher,'chat requests use the no-timeout dispatcher');assert.equal(init.headers.Accept,'text/event-stream');});
test('OpenClaw provider models go in its model header on the connection route',async t=>{const seen=[];const endpoint=await server(t,async(req,res)=>{let raw='';for await(const c of req)raw+=c;seen.push({model:JSON.parse(raw).model,header:req.headers['x-openclaw-model']});sse(res,'ok');});
  const a=new HttpAdapter({agent:{provider:'openclaw',transport:'http',endpoint,model:'openclaw/research'}});
  await a.run(context({text:'hi',conversation:{id:'c1',model:'anthropic/claude-sonnet-5'}}));
  await a.run(context({text:'hi',conversation:{id:'c1',model:''}}));
  const plain=new HttpAdapter({agent:{provider:'openclaw',transport:'http',endpoint,model:'openai/gpt-6-astra'}});await plain.run(context({text:'hi'}));
  assert.deepEqual(seen,[{model:'openclaw/research',header:'anthropic/claude-sonnet-5'},{model:'openclaw/research',header:undefined},{model:'openclaw',header:'openai/gpt-6-astra'}]);
  await assert.rejects(()=>a.run(context({text:'hi',conversation:{id:'c1',model:'bad model\r\nx: y'}})),/Choose an OpenClaw model/);});
test('OpenClaw model lists keep signed-in, configured and default models; skills and MCP servers use its formats',()=>{
  const oc=require('../desktop/openclaw.cjs');
  const r=oc.parseModels({models:[{key:'anthropic/claude-opus-5',available:false,tags:['default','configured']},{key:'claude-cli/claude-sonnet-5',available:true,tags:[]},{key:'openai/gpt-5.4',available:false,tags:[]},{key:'bad key',available:true}]});
  assert.deepEqual(r,{models:['anthropic/claude-opus-5','claude-cli/claude-sonnet-5'],default:'anthropic/claude-opus-5'});
  assert.deepEqual(oc.json('Config warnings\n{"a":1}'),{a:1});assert.throws(()=>oc.json('no json'),/no JSON/);
  assert.equal(oc.isRoute('openclaw/main'),true);assert.equal(oc.isRoute('openai/gpt'),false);
  assert.deepEqual(oc.parseSkills({skills:[{name:'1password',bundled:true,eligible:false},{name:'weather',bundled:true,eligible:true,description:'Forecasts'},{name:'mine',source:'openclaw-workspace',bundled:false,eligible:false},{name:'off',eligible:true,disabled:true}]}).map(s=>[s.name,s.category]),[['weather','bundled with OpenClaw'],['mine','workspace']]);
  assert.deepEqual(oc.mcpConfig({type:'stdio',command:'npx',args:['-y','x']},{env:{K:'v'}}),{command:'npx',args:['-y','x'],env:{K:'v'}});
  assert.deepEqual(oc.mcpConfig({type:'http',url:'https://m.example/mcp'},{headers:{Authorization:'Bearer t'}}),{url:'https://m.example/mcp',transport:'streamable-http',headers:{Authorization:'Bearer t'}});
  assert.deepEqual(oc.mcpConfig({type:'sse',url:'https://m.example/sse'},{}),{url:'https://m.example/sse'});
});
