'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');
const {Broker}=require('../desktop/broker.cjs');const {Store,Vault}=require('../desktop/store.cjs');const projects=require('../desktop/projects.cjs');const {temp,secure}=require('./helpers.cjs');
test('git actions are fixed commands with validated, quoted input for PowerShell and POSIX shells',()=>{
  const local={path:'C:\\Work\\my app',hostId:''},remote={path:'/root/app',hostId:'h1'};
  assert.equal(projects.gitCommand(local,'pull',{},{windows:true}),"Set-Location -LiteralPath 'C:\\Work\\my app'; git 'pull'");
  assert.equal(projects.gitCommand(local,'commitPush',{message:"it's done"},{windows:true}),"Set-Location -LiteralPath 'C:\\Work\\my app'; git 'add' '-A'; if ($?) { git 'commit' '-m' 'it''s done' }; if ($?) { git 'push' '-u' 'origin' 'HEAD' }");
  assert.equal(projects.gitCommand(remote,'commit',{message:'fix $(rm -rf ~)'},{windows:true}),"cd -- '/root/app' && git 'add' '-A' && git 'commit' '-m' 'fix $(rm -rf ~)'");
  assert.equal(projects.gitCommand(remote,'merge',{branch:'origin/feature/x'}),"cd -- '/root/app' && git 'merge' 'origin/feature/x'");
  assert.equal(projects.gitCommand(remote,'prCreate',{}),"cd -- '/root/app' && gh 'pr' 'create' '--fill'");
  assert.throws(()=>projects.gitCommand(remote,'switch',{branch:'--force'}),/branch name/);
  assert.throws(()=>projects.gitCommand(remote,'switch',{branch:'a;rm -rf'}),/branch name/);
  assert.throws(()=>projects.gitCommand(remote,'commit',{message:'two\nlines'}),/one line/);
  assert.throws(()=>projects.gitCommand(remote,'prCheckout',{number:'1; x'}),/number/);
  assert.throws(()=>projects.gitCommand(remote,'reset-hard',{}),/Unknown git action/);
  const clone=projects.cloneCommand({url:'https://github.com/o/repo.git',parent:'/srv',hostId:'h1'});
  assert.equal(clone.path,'/srv/repo');assert.equal(clone.command,"cd -- '/srv' && git clone 'https://github.com/o/repo.git' 'repo'");
  assert.throws(()=>projects.cloneCommand({url:'https://x.com/a b',parent:'/srv',hostId:'h1'}),/repository address/);
});
test('project chats open the agent in the project folder when it runs on that machine',async t=>{
  const root=await temp(t),runs=[];
  const broker=new Broker({store:new Store(root),vault:new Vault(root,secure()),emit:()=>{},approve:async()=>true,adapterFactory:()=>({connect:async()=>({}),close(){},run:async ctx=>{runs.push(ctx.cwd);return {};}})});
  await broker.init();t.after(()=>broker.close());
  const folder=path.resolve(root,'app');
  const local=await broker.saveAgent({agent:{name:'local',provider:'custom',protocol:'openai',transport:'http',endpoint:'http://127.0.0.1:8642/v1'}});
  const host=await broker.saveHost({alias:'vps'});
  const remote=await broker.saveAgent({agent:{name:'remote',provider:'custom',protocol:'openai',transport:'ssh',hostId:host.id,endpoint:'http://127.0.0.1:8642/v1'}});
  const p=await broker.saveProject({path:folder,agentIds:[local.id,remote.id,'missing']});
  assert.equal(p.name,'app');assert.deepEqual(p.agentIds,[local.id,remote.id]);
  await assert.rejects(()=>broker.saveProject({path:folder}),/already a project/);
  await assert.rejects(()=>broker.saveProject({path:'relative/dir'}),/absolute/);
  await assert.rejects(()=>broker.newConversation(remote.id,p.id),/different machine/);
  const c=await broker.newConversation(local.id,p.id);assert.equal(c.projectId,p.id);
  await broker.connect(local.id);await broker.send({agentId:local.id,conversationId:c.id,text:'hi'});await broker.turns.get(local.id)?.done;
  const plain=await broker.newConversation(local.id);await broker.send({agentId:local.id,conversationId:plain.id,text:'hi'});await broker.turns.get(local.id)?.done;
  assert.deepEqual(runs,[folder,'']);
  await broker.removeAgent(remote.id);assert.deepEqual(broker.project(p.id).agentIds,[local.id]);
  await broker.removeProject(p.id);assert.equal(broker.data.conversations.find(x=>x.id===c.id).projectId,undefined);
});
