'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');const path=require('node:path');const {EventEmitter}=require('node:events');const {PassThrough}=require('node:stream');
const {Rpc}=require('../desktop/rpc.cjs');const {AcpAdapter,sessionCwd,activityOf}=require('../desktop/adapters/acp.cjs');const {CodexAdapter}=require('../desktop/adapters/codex.cjs');const {ClaudeAdapter}=require('../desktop/adapters/claude.cjs');const {Terminals,dimensions}=require('../desktop/terminal.cjs');const {childMock,context}=require('./helpers.cjs');
const tick=()=>new Promise(r=>setImmediate(r));
test('RPC assembles fragmented UTF-8 frames and correlates response IDs',async()=>{const child=childMock(),rpc=new Rpc(child);const pending=rpc.request('hello',{});const bytes=Buffer.from(JSON.stringify({id:1,result:{text:'hello \u2603'}})+'\n');for(const byte of bytes)child.stdout.write(Buffer.from([byte]));assert.deepEqual(await pending,{text:'hello \u2603'});assert.equal(child.frames[0].jsonrpc,'2.0');rpc.close();});
test('RPC rejects malformed JSON and pending requests on exit',async()=>{const child=childMock(),rpc=new Rpc(child);const pending=rpc.request('hello',{});child.stdout.write('not-json\n');await assert.rejects(()=>pending,/valid JSON/);assert.equal(rpc.closed,true);});
test('RPC request timeout is bounded',async()=>{const rpc=new Rpc(childMock());await assert.rejects(()=>rpc.request('slow',{},10),/timed out/);rpc.close();});
test('RPC unsupported server requests receive errors, never automatic approval',async()=>{const child=childMock(),rpc=new Rpc(child);child.send({id:91,method:'fs/write_text_file',params:{}});await tick();assert.equal(child.frames[0].id,91);assert.equal(child.frames[0].error.code,-32601);rpc.close();});
function acpServer({loadSession=false,requestPermission=false}={}){
  return childMock((m,c)=>{
    if(m.method==='initialize')c.reply(m,{protocolVersion:1,agentCapabilities:{loadSession}});
    if(m.method==='session/new')c.reply(m,{sessionId:'acp-'+c.frames.filter(f=>f.method==='session/new').length});
    if(m.method==='session/load')c.reply(m,{});
    if(m.method==='session/prompt'){
      c.send({method:'session/update',params:{sessionId:'wrong',update:{sessionUpdate:'agent_message_chunk',content:{type:'text',text:'DO NOT MIX'}}}});
      c.send({method:'session/update',params:{sessionId:m.params.sessionId,update:{sessionUpdate:'agent_message_chunk',content:{type:'text',text:'ACP reply'}}}});
      if(requestPermission){c.prompt=m;c.send({id:991,method:'session/request_permission',params:{sessionId:m.params.sessionId,toolCall:{title:'Run test?',rawInput:{command:'npm test'}},options:[{kind:'allow_always',optionId:'always'},{kind:'allow_once',optionId:'once'}]}});}else c.reply(m,{stopReason:'end_turn'});
    }
    if(m.id===991&&!m.method)c.reply(c.prompt,{stopReason:'end_turn'});
  });
}
test('ACP session isolation, explicit allow-once approval and capability handshake',async()=>{const child=acpServer({requestPermission:true}),events=[],sessions=[];const a=new AcpAdapter({agent:{provider:'hermes',args:[],cwd:path.resolve('.')},approve:async()=>true,spawnAgent:()=>child});await a.connect();await a.run(context({onEvent:e=>events.push(e),onSession:async id=>sessions.push(id)}));assert.equal(events.map(e=>e.text).join(''),'ACP reply');assert.equal(sessions[0],'acp-1');assert.equal(child.frames.find(f=>f.id===991).result.outcome.optionId,'once');const init=child.frames.find(f=>f.method==='initialize');assert.equal(init.params.clientCapabilities.terminal,false);assert.equal(init.params.clientCapabilities.fs.writeTextFile,false);a.close();});
test('ACP exposes Hermes thinking, plan and detailed tool progress to the UI',()=>{assert.equal(activityOf({sessionUpdate:'agent_thought_chunk'}),'Thinking');assert.equal(activityOf({sessionUpdate:'plan',entries:[{content:'Inspect local gateway',status:'in_progress'}]}),'Plan 0/1: Inspect local gateway');assert.equal(activityOf({sessionUpdate:'tool_call',title:'Read config',locations:[{path:'C:\\Users\\me\\.hermes'}]}),'Read config — C:\\Users\\me\\.hermes');assert.equal(activityOf({sessionUpdate:'tool_call_update',title:'Run diagnostic',status:'completed'}),'Run diagnostic — completed');});
test('ACP uses the Hermes Docker profile as session cwd',async()=>{const child=acpServer();const agent={provider:'hermes',command:'docker',args:['exec','-i','a2a-hermes-leads','hermes'],cwd:'/root',hermesHome:'/opt/data'};const a=new AcpAdapter({agent,approve:async()=>false,spawnAgent:()=>child});assert.equal(sessionCwd(agent),'/opt/data');await a.connect();await a.run(context());assert.equal(child.frames.find(f=>f.method==='session/new').params.cwd,'/opt/data');a.close();});
test('ACP denies tools when native approval is declined',async()=>{const child=acpServer({requestPermission:true});const a=new AcpAdapter({agent:{provider:'custom',args:[],cwd:path.resolve('.')},approve:async()=>false,spawnAgent:()=>child});await a.connect();await a.run(context());assert.equal(child.frames.find(f=>f.id===991).result.outcome.outcome,'cancelled');a.close();});
test('ACP refuses to silently replay transcripts when persisted sessions cannot resume',async()=>{const a=new AcpAdapter({agent:{provider:'hermes',args:[],cwd:path.resolve('.')},approve:async()=>false,spawnAgent:()=>acpServer()});await a.connect();await assert.rejects(()=>a.run(context({conversation:{id:'x',externalSessionId:'old-process-session'}})),/cannot resume/);a.close();});
test('ACP loads the exact saved session when supported',async()=>{const child=acpServer({loadSession:true}),a=new AcpAdapter({agent:{provider:'custom',args:[],cwd:path.resolve('.')},approve:async()=>false,spawnAgent:()=>child});await a.connect();await a.run(context({conversation:{id:'x',externalSessionId:'old-session'}}));assert.equal(child.frames.find(f=>f.method==='session/load').params.sessionId,'old-session');assert.equal(child.frames.some(f=>f.method==='session/new'),false);a.close();});
function codexServer({approval=false}={}){
  const finish=(c,m)=>{const threadId=m.params.threadId;c.send({method:'item/agentMessage/delta',params:{threadId,itemId:'message-a',delta:'First'}});c.send({method:'item/completed',params:{threadId,item:{id:'message-a',type:'agentMessage',text:'First'}}});c.send({method:'item/completed',params:{threadId,item:{id:'message-b',type:'agentMessage',text:' Second'}}});c.send({method:'turn/completed',params:{threadId,turn:{id:'turn-1',status:'completed'}}});};
  return childMock((m,c)=>{
    if(m.method==='initialize')c.reply(m,{});
    if(m.method==='thread/start'||m.method==='thread/resume')c.reply(m,{thread:{id:m.params.threadId||'thread-'+c.frames.filter(f=>f.method==='thread/start').length}});
    if(m.method==='turn/start'){c.reply(m,{turn:{id:'turn-1'}});c.send({method:'turn/started',params:{threadId:m.params.threadId,turn:{id:'turn-1'}}});c.send({method:'item/agentMessage/delta',params:{threadId:'wrong-thread',delta:'DO NOT MIX'}});if(approval){c.turn=m;c.send({id:881,method:'item/commandExecution/requestApproval',params:{threadId:m.params.threadId,turnId:'turn-1',command:'npm test'}});}else finish(c,m);}
    if(m.id===881&&!m.method)finish(c,c.turn);
  });
}
test('Codex initializes without jsonrpc field, enforces approvals and streams scoped messages',async()=>{const child=codexServer({approval:true}),events=[];const a=new CodexAdapter({agent:{args:[],cwd:path.resolve('.')},approve:async()=>true,spawnAgent:()=>child});await a.connect();await a.run(context({onEvent:e=>events.push(e)}));assert.equal(child.frames[0].jsonrpc,undefined);const start=child.frames.find(f=>f.method==='thread/start');assert.equal(start.params.sandbox,'workspace-write');assert.equal(start.params.approvalPolicy,'on-request');assert.equal(child.frames.find(f=>f.id===881).result.decision,'accept');assert.equal(events.filter(e=>e.type==='text').map(e=>e.text).join(''),'First Second');a.close();});
test('Codex resumes an exact thread rather than the most recent account conversation',async()=>{const child=codexServer(),a=new CodexAdapter({agent:{args:[],cwd:path.resolve('.')},approve:async()=>false,spawnAgent:()=>child});await a.connect();await a.run(context({conversation:{id:'local-id',externalSessionId:'specific-thread'}}));assert.equal(child.frames.find(f=>f.method==='thread/resume').params.threadId,'specific-thread');a.close();});
test('Codex declining a native permission sends decline',async()=>{const child=codexServer({approval:true}),a=new CodexAdapter({agent:{args:[],cwd:path.resolve('.')},approve:async()=>false,spawnAgent:()=>child});await a.connect();await a.run(context());assert.equal(child.frames.find(f=>f.id===881).result.decision,'decline');a.close();});
test('late ACP permission responses cannot approve an already cancelled turn',async()=>{let resolveApproval;const child=acpServer({requestPermission:true}),abort=new AbortController();const a=new AcpAdapter({agent:{provider:'custom',args:[],cwd:path.resolve('.')},approve:()=>new Promise(r=>resolveApproval=r),spawnAgent:()=>child});await a.connect();const pending=a.run(context({signal:abort.signal}));await tick();abort.abort();resolveApproval(true);await assert.rejects(()=>pending,/Cancelled/);assert.equal(child.frames.find(f=>f.id===991).result.outcome.outcome,'cancelled');a.close();});
function claudeChild(events,onInput){const c=new EventEmitter();Object.assign(c,{stdin:new PassThrough(),stdout:new PassThrough(),stderr:new PassThrough(),exitCode:null,signalCode:null});c.kill=()=>{c.exitCode=0;c.emit('close',0);};let prompt='';c.stdin.on('data',d=>prompt+=d.toString());c.stdin.on('finish',()=>{onInput?.(prompt);queueMicrotask(()=>{for(const e of events)c.stdout.write(JSON.stringify(e)+'\n');c.exitCode=0;c.emit('close',0);});});return c;}
test('Claude streams partial text, uses exact --resume and keeps prompts off argv',async()=>{let argv,input;const events=[];const a=new ClaudeAdapter({agent:{args:[]},spawnAgent:(_a,args)=>{argv=args;return claudeChild([{type:'system',session_id:'claude-thread'},{type:'stream_event',event:{delta:{type:'text_delta',text:'Hi'}}},{type:'assistant',message:{content:[{type:'text',text:'Hi'}]}},{type:'result',result:'Hi',session_id:'claude-thread'}],p=>input=p);}});const result=await a.run(context({text:'secret prompt',conversation:{id:'c',externalSessionId:'exact-thread'},onEvent:e=>events.push(e)}));assert.equal(input,'secret prompt');assert(!argv.includes('secret prompt'));assert.equal(argv[argv.indexOf('--resume')+1],'exact-thread');assert(!argv.includes('--dangerously-skip-permissions'));assert.equal(events.map(e=>e.text).join(''),'Hi');assert.equal(result.externalSessionId,'claude-thread');});
test('Claude errors when a process exits before the final result',async()=>{const a=new ClaudeAdapter({agent:{args:[]},spawnAgent:()=>claudeChild([{type:'stream_event',event:{delta:{type:'text_delta',text:'partial'}}}])});await assert.rejects(()=>a.run(context()),/before a final result/);});
test('Claude headless permission denials direct the user to native terminal',async()=>{const out=[],a=new ClaudeAdapter({agent:{args:[]},spawnAgent:()=>claudeChild([{type:'result',result:'Cannot write',permission_denials:[{tool_name:'Write'}]}])});await a.run(context({onEvent:e=>out.push(e)}));assert(out.some(e=>e.type==='activity'&&e.text.includes('Terminal')));});
test('terminal sessions retain independent PTYs, bounded buffers and cleanup',()=>{const native=[],events=[];const terminal=new Terminals(e=>events.push(e),{ptyFactory:{spawn:(command,args,options)=>{const p={command,args,options,writes:[],onData:fn=>p.data=fn,onExit:fn=>p.exit=fn,write:s=>p.writes.push(s),resize:(c,r)=>p.size=[c,r],kill:()=>p.killed=true};native.push(p);return p;}}});const a={id:'a',provider:'hermes',transport:'local',cwd:path.resolve('.'),args:[]};const one=terminal.open(a,null),again=terminal.open(a,null);assert.equal(one.id,again.id);const two=terminal.open({...a,id:'b'},null);assert.notEqual(one.id,two.id);native[0].data('a'.repeat(210000));assert.equal(terminal.sessions.get(one.id).buffer.length,200000);terminal.write(one.id,'ls\r');assert.equal(native[0].writes[0],'ls\r');terminal.resize(one.id,999,999);assert.deepEqual(native[0].size,[400,200]);terminal.closeAgent('a');assert.equal(native[0].killed,true);assert.equal(terminal.sessions.size,1);terminal.closeAll();assert.equal(terminal.sessions.size,0);});
test('terminal rejects invalid dimensions and oversized input',()=>{assert.throws(()=>dimensions(NaN,30));assert.deepEqual(dimensions(1,1),{cols:20,rows:5});const t=new Terminals(()=>{},{});assert.throws(()=>t.write('x','a'.repeat(65537)),/limit/);});
